### PR TITLE
Resprites + Fixes

### PR DESCRIPTION
**Pull request by RouterXdd**
**Screenshots:**
All changed content
Снимок экрана 2023-06-16 191447

**Details:**
New sprite for shredder; resprited smelters, stockpile, core: drop, dry lumber(wood); Fixed visual weapons of crawler and swarmer (+ Fixed sprite of swarmer); changed hitsize of insects

- [X] I made sure that any changes made in this PR functions correctly in-game.

### CODE REVIEW

**Comment by RGBProductions** [comment]
*That's a lot of commits*

**Comment by RouterXdd** [comment]
Idk why they so much

**Review by JojoFR1 — CHANGES_REQUESTED** [review]
*Sigh*

In `bundle.properties`:
```
# - If you make ANY changes here please do the change in every other
#   bundles files by adding, removing or editing the line(s).
```

**Comment by SunkyMP3G** [comment]
Why the Drop pod has something white on upper-right corner?

**Pull request merged**
