### PR TITLE
Translations of "Installed version:" title + Russian translations update

### PR DESCRIPTION
**Pull request by SunkyMP3G**
Changes in menu.js, and bundles
###### *so many commits*
image

### CODE REVIEW

**Review by JojoFR1 — CHANGES_REQUESTED** [review]
Don't translate comment. It's mainly used by us, developer, to quickly find where to add/find translation.

**Review by JojoFR1 — APPROVED** [review]
Good for me, waiting for @FredyJabe review

**Comment by SunkyMP3G** [comment]
No answer...

**Comment by SunkyMP3G** [comment]
I'll remake that pull request

**Pull request closed without merging**
